version: '3'

services:
  mongoContainer:
    image: mongo
    ports:
      - "8001:8001"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - '4000:4000'
    env_file:
      - ./server/.env
    depends_on:
      - mongoContainer

volumes:
  mongo-data:
    driver: local